In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("UP_rainfall_dataset.zip")

In [3]:
df.head()

,YEAR,MO,DY,RH2M,T2MDEW,QV2M,PS,WS50M,PRECTOTCORR,T2MWET,WD50M,T2M_MAX,T2M_MIN,ALLSKY_SFC_UV_INDEX,TS,PSC,WSC,DISTRICT,LATITUDE,LONGITUDE
0,2005,1,1,56.63,9.67,7.63,99.55,3.66,0.34,14.17,135.7,26.69,14.08,0.41,19.15,90.24,5.07,Agra,27.17,78.04
1,2005,1,2,57.34,8.98,7.23,99.60,2.36,0.01,13.76,157.3,26.16,11.26,0.46,17.76,90.29,3.27,Agra,27.17,78.04
2,2005,1,3,55.19,6.25,6.12,99.79,4.27,0.33,11.35,338.1,24.76,10.65,0.32,16.40,90.39,5.91,Agra,27.17,78.04
3,2005,1,4,44.92,0.88,4.06,100.10,4.69,0.00,7.28,327.9,23.37,6.56,0.62,13.72,90.58,6.50,Agra,27.17,78.04
4,2005,1,5,45.51,0.88,4.07,99.94,4.05,0.00,7.24,338.2,23.25,5.76,0.65,13.55,90.43,5.61,Agra,27.17,78.04

In [4]:
df.tail()

,YEAR,MO,DY,RH2M,T2MDEW,QV2M,PS,WS50M,PRECTOTCORR,T2MWET,WD50M,T2M_MAX,T2M_MIN,ALLSKY_SFC_UV_INDEX,TS,PSC,WSC,DISTRICT,LATITUDE,LONGITUDE
565205,2025,11,25,77.63,11.71,8.57,100.77,4.75,0.0,13.82,275.5,23.81,10.47,0.69,15.18,90.36,6.58,Varanasi,25.31,83.01
565206,2025,11,26,72.46,10.22,7.74,100.83,3.66,0.0,12.98,281.8,23.57,9.16,0.71,14.60,90.41,5.07,Varanasi,25.31,83.01
565207,2025,11,27,69.39,10.00,7.64,100.92,2.84,0.0,12.95,297.5,23.02,10.35,0.85,14.67,90.49,3.93,Varanasi,25.31,83.01
565208,2025,11,28,77.84,11.27,8.33,100.78,4.02,0.0,13.36,278.2,22.89,9.55,0.96,14.96,90.36,5.57,Varanasi,25.31,83.01
565209,2025,11,29,80.51,12.22,8.87,100.59,4.65,0.0,14.05,269.3,23.13,10.11,0.86,15.37,90.20,6.44,Varanasi,25.31,83.01

In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 565210
Columns: 20

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565210 entries, 0 to 565209
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   YEAR                 565210 non-null  int64
 1   MO                   565210 non-null  int64
 2   DY                   565210 non-null  int64
 3   RH2M                 565210 non-null  float64
 4   T2MDEW               565210 non-null  float64
 5   QV2M                 565210 non-null  float64
 6   PS                   565210 non-null  float64
 7   WS50M                565210 non-null  float64
 8   PRECTOTCORR          565210 non-null  float64
 9   T2MWET               565210 non-null  float64
 10  WD50M                565210 non-null  float64
 11  T2M_MAX              565210 non-null  float64
 12  T2M_MIN              565210 non-null  float64
 13  ALLSKY_SFC_UV_INDEX  565210 non-null  float64
 14  TS                   565210 non-null  float64
 15  PSC                  565210 non-null  float64
 16  WSC                  565210 non-null  float64
 17  DISTRICT             565210 non-null  object
 18  LATITUDE             565210 non-null  float64
 19  LONGITUDE            565210 non-null  float64
dtypes: float64(16), int64(3), object(1)
memory usage: 86.2+ MB

In [7]:
df.dtypes

YEAR                     int64
MO                       int64
DY                       int64
RH2M                   float64
T2MDEW                 float64
QV2M                   float64
PS                     float64
WS50M                  float64
PRECTOTCORR            float64
T2MWET                 float64
WD50M                  float64
T2M_MAX                float64
T2M_MIN                float64
ALLSKY_SFC_UV_INDEX    float64
TS                     float64
PSC                    float64
WSC                    float64
DISTRICT                object
LATITUDE               float64
LONGITUDE              float64
dtype: object

In [8]:
df.isnull().sum()

YEAR                   0
MO                     0
DY                     0
RH2M                   0
T2MDEW                 0
QV2M                   0
PS                     0
WS50M                  0
PRECTOTCORR            0
T2MWET                 0
WD50M                  0
T2M_MAX                0
T2M_MIN                0
ALLSKY_SFC_UV_INDEX    0
TS                     0
PSC                    0
WSC                    0
DISTRICT               0
LATITUDE               0
LONGITUDE              0
dtype: int64

In [9]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

YEAR                   0.0
MO                     0.0
DY                     0.0
RH2M                   0.0
T2MDEW                 0.0
QV2M                   0.0
PS                     0.0
WS50M                  0.0
PRECTOTCORR            0.0
T2MWET                 0.0
WD50M                  0.0
T2M_MAX                0.0
T2M_MIN                0.0
ALLSKY_SFC_UV_INDEX    0.0
TS                     0.0
PSC                    0.0
WSC                    0.0
DISTRICT               0.0
LATITUDE               0.0
LONGITUDE              0.0
dtype: float64

In [10]:
print("Duplicate Records:", df.duplicated().sum())

Duplicate Records: 7638

In [11]:
df = df.drop_duplicates()
print("Duplicate Records After Removal:", df.duplicated().sum())

Duplicate Records After Removal: 0

In [12]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [13]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [14]:
df.isnull().sum()

YEAR                   0
MO                     0
DY                     0
RH2M                   0
T2MDEW                 0
QV2M                   0
PS                     0
WS50M                  0
PRECTOTCORR            0
T2MWET                 0
WD50M                  0
T2M_MAX                0
T2M_MIN                0
ALLSKY_SFC_UV_INDEX    0
TS                     0
PSC                    0
WSC                    0
DISTRICT               0
LATITUDE               0
LONGITUDE              0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 557572 entries, 0 to 565209
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   YEAR                 557572 non-null  int64
 1   MO                   557572 non-null  int64
 2   DY                   557572 non-null  int64
 3   RH2M                 557572 non-null  float64
 4   T2MDEW               557572 non-null  float64
 5   QV2M                 557572 non-null  float64
 6   PS                   557572 non-null  float64
 7   WS50M                557572 non-null  float64
 8   PRECTOTCORR          557572 non-null  float64
 9   T2MWET               557572 non-null  float64
 10  WD50M                557572 non-null  float64
 11  T2M_MAX              557572 non-null  float64
 12  T2M_MIN              557572 non-null  float64
 13  ALLSKY_SFC_UV_INDEX  557572 non-null  float64
 14  TS                   557572 non-null  float64
 15  PSC                  557572 non-null  float64
 16  WSC                  557572 non-null  float64
 17  DISTRICT             557572 non-null  object
 18  LATITUDE             557572 non-null  float64
 19  LONGITUDE            557572 non-null  float64
dtypes: float64(16), int64(3), object(1)
memory usage: 89.3+ MB

In [16]:
df.to_csv("UP_rainfall_cleaned.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!